services:
    web:
        image: nginx:alpine
        ports:
            - "5000:80"
        volumes:
            - .:/app
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
#        command: sh -c "chmod -R 777 /app && nginx -g 'daemon off;'"
        depends_on:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        volumes:
            - .:/app
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        depends_on:
            - db

    db:
        image: postgres
        ports:
          - "${DB_EXPOSE_PORT}:5432"
        environment:
            - POSTGRES_DB=e-auction
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
        volumes:
            - ./_docker/data/postgres:/var/lib/postgresql/data

#    pgadmin:
#      image: dpage/pgadmin4
#      environment:
#        PGADMIN_DEFAULT_EMAIL: 'admin@mail.com'
#        PGADMIN_DEFAULT_PASSWORD: 'admin'
#      volumes:
#        - pgadmin2:/root/.pgadmin
#      ports:
#        - "5001:80"
#      depends_on:
#        - db

#volumes:
#    postgres2:
#    pgadmin2:
#    vendor:
